INSERT INTO `university` (`id`, `name`) VALUES
(1, 'Ain Shams University'),
(2, 'Alexandria University'),
(3, 'Assiut University'),
(4, 'Aswan University'),
(5, 'Al-Azhar University'),
(6, 'Banha University'),
(7, 'Beni-Suef University'),
(8, 'Cairo University'),
(9, 'Damanhour University'),
(10, 'Damietta University'),
(11, 'Fayoum University'),
(12, 'Helwan University'),
(13, 'Kafrelsheikh University'),
(14, 'Mansoura University'),
(15, 'Military Technical College (MTC)'),
(16, 'Minia University'),
(17, 'Minufiya University'),
(18, 'Port Said University'),
(19, 'Sadat Academy for Management Sciences'),
(20, 'Sohag University'),
(21, 'South Valley University'),
(22, 'Suez Canal University'),
(23, 'Tanta University'),
(24, 'Zagazig University'),
(25, 'Alamein University'),
(26, 'American University in Cairo'),
(27, 'Arab Academy for Science and Technology and Maritime Transport 	'),
(28, 'Arab Open University'),
(29, 'Ahram Canadian University'),
(30, 'MTI University'),
(31, 'British University in Egypt'),
(32, 'Canadian International College'),
(33, 'Delta University for Science and Technology'),
(34, 'Egyptian e-Learning University'),
(35, 'Egyptian Russian University'),
(36, 'Cairo Private Technology Institute'),
(37, 'El Asher University'),
(38, 'El Shorouk Academy'),
(39, 'Future Academy'),
(40, 'Future University in Egypt'),
(41, 'German University in Cairo'),
(42, 'Heliopolis University'),
(43, 'Higher Technological Institute'),
(44, 'International Academy for Engineering & Media Sciences'),
(45, 'Misr International University'),
(46, 'Misr University for Science and Technology'),
(47, 'Modern Academy In Maadi'),
(48, 'Modern Sciences and Arts University'),
(49, 'Nahda University'),
(50, 'Nile University'),
(51, 'October 6 University'),
(52, 'Pharos University in Alexandria'),
(53, 'Science Valley Academy'),
(54, 'Sinai University'),
(55, 'Thebes Academy'),
(56, 'Université Senghor d''Alexandrie'),
(57, 'Université Française d’Egypte'),
(58, 'University of Science and Technology at Zewail City');